# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from super_odometry_msgs/IterationStats.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class IterationStats(genpy.Message):
  _md5sum = "90f71769f61c5a37fe60b3deb9b24f06"
  _type = "super_odometry_msgs/IterationStats"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# float64 time_elapsed
float64 translation_norm
float64 rotation_norm
float64 num_surf_from_scan
float64 num_corner_from_scan
"""
  __slots__ = ['translation_norm','rotation_norm','num_surf_from_scan','num_corner_from_scan']
  _slot_types = ['float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       translation_norm,rotation_norm,num_surf_from_scan,num_corner_from_scan

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(IterationStats, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.translation_norm is None:
        self.translation_norm = 0.
      if self.rotation_norm is None:
        self.rotation_norm = 0.
      if self.num_surf_from_scan is None:
        self.num_surf_from_scan = 0.
      if self.num_corner_from_scan is None:
        self.num_corner_from_scan = 0.
    else:
      self.translation_norm = 0.
      self.rotation_norm = 0.
      self.num_surf_from_scan = 0.
      self.num_corner_from_scan = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4d().pack(_x.translation_norm, _x.rotation_norm, _x.num_surf_from_scan, _x.num_corner_from_scan))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.translation_norm, _x.rotation_norm, _x.num_surf_from_scan, _x.num_corner_from_scan,) = _get_struct_4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4d().pack(_x.translation_norm, _x.rotation_norm, _x.num_surf_from_scan, _x.num_corner_from_scan))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.translation_norm, _x.rotation_norm, _x.num_surf_from_scan, _x.num_corner_from_scan,) = _get_struct_4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
