# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from super_odometry_msgs/LaserFeature.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import sensor_msgs.msg
import std_msgs.msg

class LaserFeature(genpy.Message):
  _md5sum = "4df4873a8473f99d913205e932f77f89"
  _type = "super_odometry_msgs/LaserFeature"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# feature Info
Header header 

int64 sensor

int64 imuAvailable
int64 odomAvailable

# IMU initial guess for laser mapping
float64 imuQuaternionX
float64 imuQuaternionY
float64 imuQuaternionZ
float64 imuQuaternionW

# Odometry initial guess for laser mapping
float64 initialPoseX
float64 initialPoseY
float64 initialPoseZ
float64 initialQuaternionX
float64 initialQuaternionY
float64 initialQuaternionZ
float64 initialQuaternionW 

# Preintegration reset ID
int64 imuPreintegrationResetId

# Point cloud messages
sensor_msgs/PointCloud2 cloud_nodistortion  # original cloud remove distortion
sensor_msgs/PointCloud2 cloud_corner    # extracted corner feature
sensor_msgs/PointCloud2 cloud_surface   # extracted surface feature
sensor_msgs/PointCloud2 cloud_realsense   # extracted surface feature from realsense
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: sensor_msgs/PointCloud2
# This message holds a collection of N-dimensional points, which may
# contain additional information such as normals, intensity, etc. The
# point data is stored as a binary blob, its layout described by the
# contents of the "fields" array.

# The point cloud data may be organized 2d (image-like) or 1d
# (unordered). Point clouds organized as 2d images may be produced by
# camera depth sensors such as stereo or time-of-flight.

# Time of sensor data acquisition, and the coordinate frame ID (for 3d
# points).
Header header

# 2D structure of the point cloud. If the cloud is unordered, height is
# 1 and width is the length of the point cloud.
uint32 height
uint32 width

# Describes the channels and their layout in the binary data blob.
PointField[] fields

bool    is_bigendian # Is this data bigendian?
uint32  point_step   # Length of a point in bytes
uint32  row_step     # Length of a row in bytes
uint8[] data         # Actual point data, size is (row_step*height)

bool is_dense        # True if there are no invalid points

================================================================================
MSG: sensor_msgs/PointField
# This message holds the description of one point entry in the
# PointCloud2 message format.
uint8 INT8    = 1
uint8 UINT8   = 2
uint8 INT16   = 3
uint8 UINT16  = 4
uint8 INT32   = 5
uint8 UINT32  = 6
uint8 FLOAT32 = 7
uint8 FLOAT64 = 8

string name      # Name of field
uint32 offset    # Offset from start of point struct
uint8  datatype  # Datatype enumeration, see above
uint32 count     # How many elements in the field
"""
  __slots__ = ['header','sensor','imuAvailable','odomAvailable','imuQuaternionX','imuQuaternionY','imuQuaternionZ','imuQuaternionW','initialPoseX','initialPoseY','initialPoseZ','initialQuaternionX','initialQuaternionY','initialQuaternionZ','initialQuaternionW','imuPreintegrationResetId','cloud_nodistortion','cloud_corner','cloud_surface','cloud_realsense']
  _slot_types = ['std_msgs/Header','int64','int64','int64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','int64','sensor_msgs/PointCloud2','sensor_msgs/PointCloud2','sensor_msgs/PointCloud2','sensor_msgs/PointCloud2']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,sensor,imuAvailable,odomAvailable,imuQuaternionX,imuQuaternionY,imuQuaternionZ,imuQuaternionW,initialPoseX,initialPoseY,initialPoseZ,initialQuaternionX,initialQuaternionY,initialQuaternionZ,initialQuaternionW,imuPreintegrationResetId,cloud_nodistortion,cloud_corner,cloud_surface,cloud_realsense

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LaserFeature, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.sensor is None:
        self.sensor = 0
      if self.imuAvailable is None:
        self.imuAvailable = 0
      if self.odomAvailable is None:
        self.odomAvailable = 0
      if self.imuQuaternionX is None:
        self.imuQuaternionX = 0.
      if self.imuQuaternionY is None:
        self.imuQuaternionY = 0.
      if self.imuQuaternionZ is None:
        self.imuQuaternionZ = 0.
      if self.imuQuaternionW is None:
        self.imuQuaternionW = 0.
      if self.initialPoseX is None:
        self.initialPoseX = 0.
      if self.initialPoseY is None:
        self.initialPoseY = 0.
      if self.initialPoseZ is None:
        self.initialPoseZ = 0.
      if self.initialQuaternionX is None:
        self.initialQuaternionX = 0.
      if self.initialQuaternionY is None:
        self.initialQuaternionY = 0.
      if self.initialQuaternionZ is None:
        self.initialQuaternionZ = 0.
      if self.initialQuaternionW is None:
        self.initialQuaternionW = 0.
      if self.imuPreintegrationResetId is None:
        self.imuPreintegrationResetId = 0
      if self.cloud_nodistortion is None:
        self.cloud_nodistortion = sensor_msgs.msg.PointCloud2()
      if self.cloud_corner is None:
        self.cloud_corner = sensor_msgs.msg.PointCloud2()
      if self.cloud_surface is None:
        self.cloud_surface = sensor_msgs.msg.PointCloud2()
      if self.cloud_realsense is None:
        self.cloud_realsense = sensor_msgs.msg.PointCloud2()
    else:
      self.header = std_msgs.msg.Header()
      self.sensor = 0
      self.imuAvailable = 0
      self.odomAvailable = 0
      self.imuQuaternionX = 0.
      self.imuQuaternionY = 0.
      self.imuQuaternionZ = 0.
      self.imuQuaternionW = 0.
      self.initialPoseX = 0.
      self.initialPoseY = 0.
      self.initialPoseZ = 0.
      self.initialQuaternionX = 0.
      self.initialQuaternionY = 0.
      self.initialQuaternionZ = 0.
      self.initialQuaternionW = 0.
      self.imuPreintegrationResetId = 0
      self.cloud_nodistortion = sensor_msgs.msg.PointCloud2()
      self.cloud_corner = sensor_msgs.msg.PointCloud2()
      self.cloud_surface = sensor_msgs.msg.PointCloud2()
      self.cloud_realsense = sensor_msgs.msg.PointCloud2()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3q11dq3I().pack(_x.sensor, _x.imuAvailable, _x.odomAvailable, _x.imuQuaternionX, _x.imuQuaternionY, _x.imuQuaternionZ, _x.imuQuaternionW, _x.initialPoseX, _x.initialPoseY, _x.initialPoseZ, _x.initialQuaternionX, _x.initialQuaternionY, _x.initialQuaternionZ, _x.initialQuaternionW, _x.imuPreintegrationResetId, _x.cloud_nodistortion.header.seq, _x.cloud_nodistortion.header.stamp.secs, _x.cloud_nodistortion.header.stamp.nsecs))
      _x = self.cloud_nodistortion.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.cloud_nodistortion.height, _x.cloud_nodistortion.width))
      length = len(self.cloud_nodistortion.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.cloud_nodistortion.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.cloud_nodistortion.is_bigendian, _x.cloud_nodistortion.point_step, _x.cloud_nodistortion.row_step))
      _x = self.cloud_nodistortion.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.cloud_nodistortion.is_dense, _x.cloud_corner.header.seq, _x.cloud_corner.header.stamp.secs, _x.cloud_corner.header.stamp.nsecs))
      _x = self.cloud_corner.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.cloud_corner.height, _x.cloud_corner.width))
      length = len(self.cloud_corner.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.cloud_corner.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.cloud_corner.is_bigendian, _x.cloud_corner.point_step, _x.cloud_corner.row_step))
      _x = self.cloud_corner.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.cloud_corner.is_dense, _x.cloud_surface.header.seq, _x.cloud_surface.header.stamp.secs, _x.cloud_surface.header.stamp.nsecs))
      _x = self.cloud_surface.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.cloud_surface.height, _x.cloud_surface.width))
      length = len(self.cloud_surface.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.cloud_surface.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.cloud_surface.is_bigendian, _x.cloud_surface.point_step, _x.cloud_surface.row_step))
      _x = self.cloud_surface.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.cloud_surface.is_dense, _x.cloud_realsense.header.seq, _x.cloud_realsense.header.stamp.secs, _x.cloud_realsense.header.stamp.nsecs))
      _x = self.cloud_realsense.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.cloud_realsense.height, _x.cloud_realsense.width))
      length = len(self.cloud_realsense.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.cloud_realsense.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.cloud_realsense.is_bigendian, _x.cloud_realsense.point_step, _x.cloud_realsense.row_step))
      _x = self.cloud_realsense.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.cloud_realsense.is_dense
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.cloud_nodistortion is None:
        self.cloud_nodistortion = sensor_msgs.msg.PointCloud2()
      if self.cloud_corner is None:
        self.cloud_corner = sensor_msgs.msg.PointCloud2()
      if self.cloud_surface is None:
        self.cloud_surface = sensor_msgs.msg.PointCloud2()
      if self.cloud_realsense is None:
        self.cloud_realsense = sensor_msgs.msg.PointCloud2()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 132
      (_x.sensor, _x.imuAvailable, _x.odomAvailable, _x.imuQuaternionX, _x.imuQuaternionY, _x.imuQuaternionZ, _x.imuQuaternionW, _x.initialPoseX, _x.initialPoseY, _x.initialPoseZ, _x.initialQuaternionX, _x.initialQuaternionY, _x.initialQuaternionZ, _x.initialQuaternionW, _x.imuPreintegrationResetId, _x.cloud_nodistortion.header.seq, _x.cloud_nodistortion.header.stamp.secs, _x.cloud_nodistortion.header.stamp.nsecs,) = _get_struct_3q11dq3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cloud_nodistortion.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cloud_nodistortion.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.cloud_nodistortion.height, _x.cloud_nodistortion.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cloud_nodistortion.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.cloud_nodistortion.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.cloud_nodistortion.is_bigendian, _x.cloud_nodistortion.point_step, _x.cloud_nodistortion.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.cloud_nodistortion.is_bigendian = bool(self.cloud_nodistortion.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.cloud_nodistortion.data = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.cloud_nodistortion.is_dense, _x.cloud_corner.header.seq, _x.cloud_corner.header.stamp.secs, _x.cloud_corner.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.cloud_nodistortion.is_dense = bool(self.cloud_nodistortion.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cloud_corner.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cloud_corner.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.cloud_corner.height, _x.cloud_corner.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cloud_corner.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.cloud_corner.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.cloud_corner.is_bigendian, _x.cloud_corner.point_step, _x.cloud_corner.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.cloud_corner.is_bigendian = bool(self.cloud_corner.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.cloud_corner.data = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.cloud_corner.is_dense, _x.cloud_surface.header.seq, _x.cloud_surface.header.stamp.secs, _x.cloud_surface.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.cloud_corner.is_dense = bool(self.cloud_corner.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cloud_surface.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cloud_surface.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.cloud_surface.height, _x.cloud_surface.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cloud_surface.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.cloud_surface.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.cloud_surface.is_bigendian, _x.cloud_surface.point_step, _x.cloud_surface.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.cloud_surface.is_bigendian = bool(self.cloud_surface.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.cloud_surface.data = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.cloud_surface.is_dense, _x.cloud_realsense.header.seq, _x.cloud_realsense.header.stamp.secs, _x.cloud_realsense.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.cloud_surface.is_dense = bool(self.cloud_surface.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cloud_realsense.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cloud_realsense.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.cloud_realsense.height, _x.cloud_realsense.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cloud_realsense.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.cloud_realsense.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.cloud_realsense.is_bigendian, _x.cloud_realsense.point_step, _x.cloud_realsense.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.cloud_realsense.is_bigendian = bool(self.cloud_realsense.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.cloud_realsense.data = str[start:end]
      start = end
      end += 1
      (self.cloud_realsense.is_dense,) = _get_struct_B().unpack(str[start:end])
      self.cloud_realsense.is_dense = bool(self.cloud_realsense.is_dense)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3q11dq3I().pack(_x.sensor, _x.imuAvailable, _x.odomAvailable, _x.imuQuaternionX, _x.imuQuaternionY, _x.imuQuaternionZ, _x.imuQuaternionW, _x.initialPoseX, _x.initialPoseY, _x.initialPoseZ, _x.initialQuaternionX, _x.initialQuaternionY, _x.initialQuaternionZ, _x.initialQuaternionW, _x.imuPreintegrationResetId, _x.cloud_nodistortion.header.seq, _x.cloud_nodistortion.header.stamp.secs, _x.cloud_nodistortion.header.stamp.nsecs))
      _x = self.cloud_nodistortion.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.cloud_nodistortion.height, _x.cloud_nodistortion.width))
      length = len(self.cloud_nodistortion.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.cloud_nodistortion.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.cloud_nodistortion.is_bigendian, _x.cloud_nodistortion.point_step, _x.cloud_nodistortion.row_step))
      _x = self.cloud_nodistortion.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.cloud_nodistortion.is_dense, _x.cloud_corner.header.seq, _x.cloud_corner.header.stamp.secs, _x.cloud_corner.header.stamp.nsecs))
      _x = self.cloud_corner.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.cloud_corner.height, _x.cloud_corner.width))
      length = len(self.cloud_corner.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.cloud_corner.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.cloud_corner.is_bigendian, _x.cloud_corner.point_step, _x.cloud_corner.row_step))
      _x = self.cloud_corner.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.cloud_corner.is_dense, _x.cloud_surface.header.seq, _x.cloud_surface.header.stamp.secs, _x.cloud_surface.header.stamp.nsecs))
      _x = self.cloud_surface.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.cloud_surface.height, _x.cloud_surface.width))
      length = len(self.cloud_surface.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.cloud_surface.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.cloud_surface.is_bigendian, _x.cloud_surface.point_step, _x.cloud_surface.row_step))
      _x = self.cloud_surface.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.cloud_surface.is_dense, _x.cloud_realsense.header.seq, _x.cloud_realsense.header.stamp.secs, _x.cloud_realsense.header.stamp.nsecs))
      _x = self.cloud_realsense.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.cloud_realsense.height, _x.cloud_realsense.width))
      length = len(self.cloud_realsense.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.cloud_realsense.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.cloud_realsense.is_bigendian, _x.cloud_realsense.point_step, _x.cloud_realsense.row_step))
      _x = self.cloud_realsense.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.cloud_realsense.is_dense
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.cloud_nodistortion is None:
        self.cloud_nodistortion = sensor_msgs.msg.PointCloud2()
      if self.cloud_corner is None:
        self.cloud_corner = sensor_msgs.msg.PointCloud2()
      if self.cloud_surface is None:
        self.cloud_surface = sensor_msgs.msg.PointCloud2()
      if self.cloud_realsense is None:
        self.cloud_realsense = sensor_msgs.msg.PointCloud2()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 132
      (_x.sensor, _x.imuAvailable, _x.odomAvailable, _x.imuQuaternionX, _x.imuQuaternionY, _x.imuQuaternionZ, _x.imuQuaternionW, _x.initialPoseX, _x.initialPoseY, _x.initialPoseZ, _x.initialQuaternionX, _x.initialQuaternionY, _x.initialQuaternionZ, _x.initialQuaternionW, _x.imuPreintegrationResetId, _x.cloud_nodistortion.header.seq, _x.cloud_nodistortion.header.stamp.secs, _x.cloud_nodistortion.header.stamp.nsecs,) = _get_struct_3q11dq3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cloud_nodistortion.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cloud_nodistortion.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.cloud_nodistortion.height, _x.cloud_nodistortion.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cloud_nodistortion.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.cloud_nodistortion.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.cloud_nodistortion.is_bigendian, _x.cloud_nodistortion.point_step, _x.cloud_nodistortion.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.cloud_nodistortion.is_bigendian = bool(self.cloud_nodistortion.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.cloud_nodistortion.data = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.cloud_nodistortion.is_dense, _x.cloud_corner.header.seq, _x.cloud_corner.header.stamp.secs, _x.cloud_corner.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.cloud_nodistortion.is_dense = bool(self.cloud_nodistortion.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cloud_corner.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cloud_corner.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.cloud_corner.height, _x.cloud_corner.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cloud_corner.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.cloud_corner.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.cloud_corner.is_bigendian, _x.cloud_corner.point_step, _x.cloud_corner.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.cloud_corner.is_bigendian = bool(self.cloud_corner.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.cloud_corner.data = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.cloud_corner.is_dense, _x.cloud_surface.header.seq, _x.cloud_surface.header.stamp.secs, _x.cloud_surface.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.cloud_corner.is_dense = bool(self.cloud_corner.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cloud_surface.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cloud_surface.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.cloud_surface.height, _x.cloud_surface.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cloud_surface.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.cloud_surface.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.cloud_surface.is_bigendian, _x.cloud_surface.point_step, _x.cloud_surface.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.cloud_surface.is_bigendian = bool(self.cloud_surface.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.cloud_surface.data = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.cloud_surface.is_dense, _x.cloud_realsense.header.seq, _x.cloud_realsense.header.stamp.secs, _x.cloud_realsense.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.cloud_surface.is_dense = bool(self.cloud_surface.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cloud_realsense.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cloud_realsense.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.cloud_realsense.height, _x.cloud_realsense.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cloud_realsense.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.cloud_realsense.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.cloud_realsense.is_bigendian, _x.cloud_realsense.point_step, _x.cloud_realsense.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.cloud_realsense.is_bigendian = bool(self.cloud_realsense.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.cloud_realsense.data = str[start:end]
      start = end
      end += 1
      (self.cloud_realsense.is_dense,) = _get_struct_B().unpack(str[start:end])
      self.cloud_realsense.is_dense = bool(self.cloud_realsense.is_dense)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3q11dq3I = None
def _get_struct_3q11dq3I():
    global _struct_3q11dq3I
    if _struct_3q11dq3I is None:
        _struct_3q11dq3I = struct.Struct("<3q11dq3I")
    return _struct_3q11dq3I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_B2I = None
def _get_struct_B2I():
    global _struct_B2I
    if _struct_B2I is None:
        _struct_B2I = struct.Struct("<B2I")
    return _struct_B2I
_struct_B3I = None
def _get_struct_B3I():
    global _struct_B3I
    if _struct_B3I is None:
        _struct_B3I = struct.Struct("<B3I")
    return _struct_B3I
_struct_IBI = None
def _get_struct_IBI():
    global _struct_IBI
    if _struct_IBI is None:
        _struct_IBI = struct.Struct("<IBI")
    return _struct_IBI
