name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        run: |
          cd client && npm i --legacy-peer-deps

      - name: Run ESLint
        run: cd client && npm run lint
        continue-on-error: false

  black:
    name: Run Black
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install Black
        run: |
          pip3 install black

      - name: Run Black
        run: black --check --verbose .
        continue-on-error: false

  build:
    name: Check Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Save previous build
        run: cd client && mv build build1

      - name: Install Project
        run: |
          cd client && npm i --legacy-peer-deps && npm run build

      - name: Check build
        run: cd client && node checkBuild.js
        continue-on-error: false
